#ifndef CBCTRECON_TEST_HPP
#define CBCTRECON_TEST_HPP

/* Defines necessary for using TinyRefl */

#define TINYREFL_API_CODEGEN_VERSION_MAJOR 0
#define TINYREFL_API_CODEGEN_VERSION_MINOR 1
#define TINYREFL_API_CODEGEN_VERSION_FIX   1

#endif // CBCTRECON_TEST_HPP
