message (STATUS "Hello from ExternalITK")

ExternalProject_Add(ITKv120
  SOURCE_DIR ${ITK_SRC_DIR}
  BINARY_DIR ${ITK_BUILD_DIR}
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DITK_BUILD_DEFAULT_MODULES:BOOL=OFF
    -DITKGroup_Core:BOOL=ON
    -DITKGroup_IO:BOOL=ON
    -DModule_ITKReview:BOOL=OFF
    -DModule_ITKDCMTK:BOOL=OFF
    -DITK_LEGACY_SILENT:BOOL=ON
    -DITK_USE_KWSTYLE:BOOL=OFF
    -DITK_COMPUTER_MEMORY_SIZE:STRING=${MEMORY_SIZE}
    -DExternalData_OBJECT_STORES:STRING=${ExternalData_OBJECT_STORES}
  INSTALL_COMMAND ""
  ## LOG_BUILD 0
)

SET(ITK_DIR ${ITK_BUILD_DIR})
